/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/agent/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Analyst Tickets */
    get: operations["analyst_tickets_api_v1_agent_tickets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agent/tickets/{ticket_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Analyst Ticket */
    get: operations["analyst_ticket_api_v1_agent_tickets__ticket_key__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agent/tickets/{ticket_key}/assignment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Assign Ticket */
    post: operations["assign_ticket_api_v1_agent_tickets__ticket_key__assignment_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agent/tickets/{ticket_key}/route": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Route Ticket */
    post: operations["route_ticket_api_v1_agent_tickets__ticket_key__route_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/agent/tickets/{ticket_key}/transitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Available Transitions */
    get: operations["available_transitions_api_v1_agent_tickets__ticket_key__transitions_get"];
    put?: never;
    /** Execute Transition */
    post: operations["execute_transition_api_v1_agent_tickets__ticket_key__transitions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Projects */
    get: operations["list_projects_api_v1_catalog_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_v1_catalog_projects__project_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/projects/{project_id}/request-types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Request Types */
    get: operations["list_request_types_api_v1_catalog_projects__project_id__request_types_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/projects/{project_id}/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Services */
    get: operations["list_services_api_v1_catalog_projects__project_id__services_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/request-types/{request_type_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Request Type */
    get: operations["get_request_type_api_v1_catalog_request_types__request_type_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/request-types/{request_type_id}/form": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Request Form */
    get: operations["get_request_form_api_v1_catalog_request_types__request_type_id__form_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/identity/diagnostics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Identity Diagnostics */
    get: operations["identity_diagnostics_api_v1_identity_diagnostics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current Identity */
    get: operations["current_identity_api_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/my/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Tickets */
    get: operations["my_tickets_api_v1_my_tickets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ticket-drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Draft */
    post: operations["create_draft_api_v1_ticket_drafts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ticket-drafts/{draft_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Draft */
    get: operations["get_draft_api_v1_ticket_drafts__draft_id__get"];
    put?: never;
    post?: never;
    /** Cancel Draft */
    delete: operations["cancel_draft_api_v1_ticket_drafts__draft_id__delete"];
    options?: never;
    head?: never;
    /** Update Draft */
    patch: operations["update_draft_api_v1_ticket_drafts__draft_id__patch"];
    trace?: never;
  };
  "/api/v1/ticket-drafts/{draft_id}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Draft */
    post: operations["submit_draft_api_v1_ticket_drafts__draft_id__submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ticket-drafts/{draft_id}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate Draft */
    post: operations["validate_draft_api_v1_ticket_drafts__draft_id__validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tickets/{ticket_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Ticket */
    get: operations["get_ticket_api_v1_tickets__ticket_key__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tickets/{ticket_key}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Public Comment */
    post: operations["add_public_comment_api_v1_tickets__ticket_key__comments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssignmentResponse */
    AssignmentResponse: {
      /** Assignee User Id */
      assignee_user_id: string | null;
      /** Assignment Group Code */
      assignment_group_code: string;
      /**
       * Fallback
       * @default false
       */
      fallback: boolean;
      /**
       * Replayed
       * @default false
       */
      replayed: boolean;
      /** Routing Rule Version Id */
      routing_rule_version_id?: string | null;
      ticket: components["schemas"]["TicketResponse"];
    };
    /** AvailableTransition */
    AvailableTransition: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** To Status */
      to_status: string;
      /** To Status Name */
      to_status_name: string;
    };
    /** AvailableTransitionList */
    AvailableTransitionList: {
      /** Current Status */
      current_status: string;
      /** Row Version */
      row_version: number;
      /** Ticket Key */
      ticket_key: string;
      /** Transitions */
      transitions: components["schemas"]["AvailableTransition"][];
    };
    /** ConditionPredicate */
    ConditionPredicate: {
      /** Field */
      field: string;
      /**
       * Operator
       * @enum {string}
       */
      operator:
        "equals" | "not_equals" | "in" | "not_in" | "is_empty" | "is_not_empty";
      /** Value */
      value?:
        string | number | boolean | (string | number | boolean | null)[] | null;
    };
    /** ConditionalRule */
    ConditionalRule: {
      /** All */
      all?: components["schemas"]["ConditionPredicate"][] | null;
      /** Any */
      any?: components["schemas"]["ConditionPredicate"][] | null;
    };
    /** CurrentIdentityResponse */
    CurrentIdentityResponse: {
      /**
       * Authentication Mode
       * @enum {string}
       */
      authentication_mode: "developer_header" | "oidc";
      /** Business Unit Id */
      business_unit_id: string | null;
      /** Business Unit Name */
      business_unit_name: string | null;
      /** Display Name */
      display_name: string;
      /** Provider Code */
      provider_code?: string | null;
      /** Role Codes */
      role_codes: string[];
      /** Support Group Ids */
      support_group_ids: string[];
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** CustomFieldInput */
    CustomFieldInput: {
      /** Field Code */
      field_code: string;
      /** Value */
      value: unknown;
    };
    /** DependencyHealth */
    DependencyHealth: {
      /** Duration Ms */
      duration_ms: number;
      /** Required */
      required: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "unhealthy" | "disabled";
    };
    /** DraftCreateRequest */
    DraftCreateRequest: {
      /** Application Environment Id */
      application_environment_id?: string | null;
      /** Custom Fields */
      custom_fields?: components["schemas"]["CustomFieldInput"][];
      /** Description */
      description?: string | null;
      /** Impact */
      impact: string;
      /**
       * Request Type Id
       * Format: uuid
       */
      request_type_id: string;
      /** Requested For User Id */
      requested_for_user_id?: string | null;
      /** Service Node Id */
      service_node_id?: string | null;
      /** Summary */
      summary: string;
      /** Urgency */
      urgency: string;
    };
    /** DraftPatchRequest */
    DraftPatchRequest: {
      /** Application Environment Id */
      application_environment_id?: string | null;
      /** Custom Fields */
      custom_fields?: components["schemas"]["CustomFieldInput"][] | null;
      /** Description */
      description?: string | null;
      /** Impact */
      impact?: string | null;
      /** Requested For User Id */
      requested_for_user_id?: string | null;
      /** Row Version */
      row_version: number;
      /** Service Node Id */
      service_node_id?: string | null;
      /** Summary */
      summary?: string | null;
      /** Urgency */
      urgency?: string | null;
    };
    /** DraftResponse */
    DraftResponse: {
      /** Application Environment Id */
      application_environment_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Custom Fields */
      custom_fields: components["schemas"]["NormalizedField"][];
      /** Description */
      description: string | null;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Impact */
      impact: string | null;
      /**
       * Owner User Id
       * Format: uuid
       */
      owner_user_id: string;
      /** Priority */
      priority: string | null;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Request Type Id
       * Format: uuid
       */
      request_type_id: string;
      /**
       * Request Type Version Id
       * Format: uuid
       */
      request_type_version_id: string;
      /** Requested For User Id */
      requested_for_user_id: string | null;
      /** Row Version */
      row_version: number;
      /** Service Node Id */
      service_node_id: string | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        "DRAFT" | "READY_FOR_REVIEW" | "SUBMITTED" | "EXPIRED" | "CANCELLED";
      /** Submitted Ticket Key */
      submitted_ticket_key?: string | null;
      /** Summary */
      summary: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Urgency */
      urgency: string | null;
    };
    /** DraftValidationResponse */
    DraftValidationResponse: {
      draft: components["schemas"]["DraftResponse"];
      /**
       * Valid
       * @default true
       * @constant
       */
      valid: true;
    };
    /** DraftVersionRequest */
    DraftVersionRequest: {
      /** Row Version */
      row_version: number;
    };
    /** FieldOptionResponse */
    FieldOptionResponse: {
      /** Display Order */
      display_order: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Label */
      label: string;
      /** Value */
      value: string;
    };
    /** FieldValidationResponse */
    FieldValidationResponse: {
      /** Maximum */
      maximum?: string | null;
      /** Maximum Items */
      maximum_items?: number | null;
      /** Maximum Length */
      maximum_length?: number | null;
      /** Minimum */
      minimum?: string | null;
      /** Minimum Items */
      minimum_items?: number | null;
      /** Minimum Length */
      minimum_length?: number | null;
      /** Pattern */
      pattern?: string | null;
    };
    /** FormFieldResponse */
    FormFieldResponse: {
      condition: components["schemas"]["ConditionalRule"] | null;
      /**
       * Data Type
       * @enum {string}
       */
      data_type:
        | "TEXT"
        | "LONG_TEXT"
        | "NUMBER"
        | "DATE"
        | "TIMESTAMP"
        | "BOOLEAN"
        | "SINGLE_SELECT"
        | "MULTI_SELECT"
        | "USER"
        | "GROUP"
        | "SERVICE"
        | "MODULE"
        | "ASSET"
        | "JSON_OBJECT";
      default_value?: components["schemas"]["JsonValue"];
      /** Description */
      description: string | null;
      /** Display Order */
      display_order: number;
      /** Field Code */
      field_code: string;
      /**
       * Field Id
       * Format: uuid
       */
      field_id: string;
      /** Label */
      label: string;
      /** Options */
      options: components["schemas"]["FieldOptionResponse"][];
      /** Required */
      required: boolean;
      validation: components["schemas"]["FieldValidationResponse"];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Correlation Id */
      correlation_id: string;
      /** Dependencies */
      dependencies: {
        [key: string]: components["schemas"]["DependencyHealth"];
      };
      /** Duration Ms */
      duration_ms: number;
      /** Environment */
      environment: string;
      /** Service */
      service: string;
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "unhealthy";
      /** Version */
      version: string;
    };
    /** IdentityDiagnosticResponse */
    IdentityDiagnosticResponse: {
      /** Allowed Algorithms */
      allowed_algorithms: string[];
      /** Audience Configured */
      audience_configured: boolean;
      /**
       * Authentication Mode
       * @enum {string}
       */
      authentication_mode: "developer_header" | "oidc";
      /** Group Synchronization Enabled */
      group_synchronization_enabled: boolean;
      /** Issuer Configured */
      issuer_configured: boolean;
      /** Jit Provisioning Enabled */
      jit_provisioning_enabled: boolean;
      /** Metrics */
      metrics: {
        [key: string]: unknown;
      };
      /** Oidc Enabled */
      oidc_enabled: boolean;
      /** Profile Synchronization Enabled */
      profile_synchronization_enabled: boolean;
      /** Provider Code */
      provider_code: string | null;
      /**
       * Status
       * @constant
       */
      status: "authorized";
    };
    JsonValue: unknown;
    /** ManualAssignmentCommand */
    ManualAssignmentCommand: {
      /** Assignee User Id */
      assignee_user_id?: string | null;
      /**
       * Assignment Group Id
       * Format: uuid
       */
      assignment_group_id: string;
      /** Reason */
      reason: string;
      /** Row Version */
      row_version: number;
    };
    /** NormalizedField */
    NormalizedField: {
      /** Data Type */
      data_type: string;
      /** Field Code */
      field_code: string;
      /** Value */
      value:
        | string
        | boolean
        | string[]
        | {
            [key: string]: unknown;
          }
        | null;
    };
    /** PageMetadata */
    PageMetadata: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Returned */
      returned: number;
    };
    /** ProblemResponse */
    ProblemResponse: {
      /** Correlation Id */
      correlation_id: string;
      /** Detail */
      detail: string;
      /** Errors */
      errors?: {
        [key: string]: string[];
      } | null;
      /** Instance */
      instance: string;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /** ProjectListResponse */
    ProjectListResponse: {
      /** Items */
      items: components["schemas"]["ProjectResponse"][];
      page: components["schemas"]["PageMetadata"];
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** Code */
      code: string;
      /** Default Timezone */
      default_timezone: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** PublicCommentCreateRequest */
    PublicCommentCreateRequest: {
      /** Body */
      body: string;
    };
    /** PublicCommentResponse */
    PublicCommentResponse: {
      /** Author Name */
      author_name: string;
      /**
       * Author User Id
       * Format: uuid
       */
      author_user_id: string;
      /** Body */
      body: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** RequestFormResponse */
    RequestFormResponse: {
      /** Code */
      code: string;
      /** Description */
      description: string | null;
      /** Effective From */
      effective_from: string | null;
      /** Effective To */
      effective_to: string | null;
      /**
       * Evaluated At
       * Format: date-time
       */
      evaluated_at: string;
      /** Fields */
      fields: components["schemas"]["FormFieldResponse"][];
      /** Name */
      name: string;
      project: components["schemas"]["ProjectResponse"];
      /**
       * Request Type Id
       * Format: uuid
       */
      request_type_id: string;
      /**
       * Request Type Version Id
       * Format: uuid
       */
      request_type_version_id: string;
      /** Version Number */
      version_number: number;
      work_type: components["schemas"]["WorkTypeResponse"];
    };
    /** RequestTypeListResponse */
    RequestTypeListResponse: {
      /**
       * Evaluated At
       * Format: date-time
       */
      evaluated_at: string;
      /** Items */
      items: components["schemas"]["RequestTypeResponse"][];
      page: components["schemas"]["PageMetadata"];
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
    };
    /** RequestTypeResponse */
    RequestTypeResponse: {
      /** Code */
      code: string;
      /** Description */
      description: string | null;
      /** Display Order */
      display_order: number;
      /** Effective From */
      effective_from: string | null;
      /** Effective To */
      effective_to: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Portal Group */
      portal_group: string | null;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
      /** Version Number */
      version_number: number;
      work_type: components["schemas"]["WorkTypeResponse"];
    };
    /** RouteCommand */
    RouteCommand: {
      /** Row Version */
      row_version: number;
    };
    /** ServiceNodeListResponse */
    ServiceNodeListResponse: {
      /** Items */
      items: components["schemas"]["ServiceNodeResponse"][];
      page: components["schemas"]["PageMetadata"];
      /** Parent Id */
      parent_id: string | null;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
    };
    /** ServiceNodeResponse */
    ServiceNodeResponse: {
      /** Code */
      code: string;
      /** Criticality */
      criticality: string | null;
      /** Data Classification */
      data_classification: string;
      /** Display Order */
      display_order: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Node Type */
      node_type: string;
      /** Parent Id */
      parent_id: string | null;
    };
    /** TicketPage */
    TicketPage: {
      /** Items */
      items: components["schemas"]["TicketResponse"][];
      /** Limit */
      limit: number;
      /**
       * Next Cursor
       * @description Opaque keyset cursor
       */
      next_cursor?: string | null;
    };
    /** TicketResponse */
    TicketResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Creation Event At */
      creation_event_at: string | null;
      /** Description */
      description: string | null;
      /** Environment Name */
      environment_name: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Key */
      key: string;
      /** Priority */
      priority: string;
      /** Project Code */
      project_code: string;
      /** Project Name */
      project_name: string;
      /** Public Comments */
      public_comments?: components["schemas"]["PublicCommentResponse"][];
      /** Reporter Name */
      reporter_name: string;
      /**
       * Reporter User Id
       * Format: uuid
       */
      reporter_user_id: string;
      /** Request Type Code */
      request_type_code: string;
      /** Request Type Name */
      request_type_name: string;
      /** Requested For Name */
      requested_for_name: string | null;
      /** Requested For User Id */
      requested_for_user_id: string | null;
      /** Row Version */
      row_version: number;
      /** Service Name */
      service_name: string | null;
      /** Status */
      status: string;
      /** Status Name */
      status_name: string;
      /** Summary */
      summary: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Work Type */
      work_type: string;
    };
    /** TransitionCommand */
    TransitionCommand: {
      /** Comment */
      comment?: string | null;
      /** Field Updates */
      field_updates?: {
        [key: string]: unknown;
      };
      /** Row Version */
      row_version: number;
      /** Transition Code */
      transition_code: string;
    };
    /** TransitionResponse */
    TransitionResponse: {
      /**
       * Replayed
       * @default false
       */
      replayed: boolean;
      ticket: components["schemas"]["TicketResponse"];
      /** Transition Code */
      transition_code: string;
    };
    /** WorkTypeResponse */
    WorkTypeResponse: {
      /** Code */
      code: string;
      /** Name */
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  analyst_tickets_api_v1_agent_tickets_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketPage"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  analyst_ticket_api_v1_agent_tickets__ticket_key__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  assign_ticket_api_v1_agent_tickets__ticket_key__assignment_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "If-Match"?: string | null;
      };
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManualAssignmentCommand"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssignmentResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Ticket not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Routing or concurrency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Assignment validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  route_ticket_api_v1_agent_tickets__ticket_key__route_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "If-Match"?: string | null;
      };
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RouteCommand"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssignmentResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Ticket not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Routing or concurrency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Assignment validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  available_transitions_api_v1_agent_tickets__ticket_key__transitions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvailableTransitionList"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Ticket not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid or concurrent transition */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Transition validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  execute_transition_api_v1_agent_tickets__ticket_key__transitions_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "If-Match"?: string | null;
      };
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionCommand"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransitionResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Ticket not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid or concurrent transition */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Transition validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  list_projects_api_v1_catalog_projects_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectListResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  get_project_api_v1_catalog_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  list_request_types_api_v1_catalog_projects__project_id__request_types_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestTypeListResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  list_services_api_v1_catalog_projects__project_id__services_get: {
    parameters: {
      query?: {
        parent_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceNodeListResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  get_request_type_api_v1_catalog_request_types__request_type_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_type_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestTypeResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  get_request_form_api_v1_catalog_request_types__request_type_id__form_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_type_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequestFormResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Catalogue resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Published configuration conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Invalid request parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  readiness_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  identity_diagnostics_api_v1_identity_diagnostics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityDiagnosticResponse"];
        };
      };
    };
  };
  current_identity_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentIdentityResponse"];
        };
      };
    };
  };
  my_tickets_api_v1_my_tickets_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketPage"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  create_draft_api_v1_ticket_drafts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  get_draft_api_v1_ticket_drafts__draft_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        draft_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  cancel_draft_api_v1_ticket_drafts__draft_id__delete: {
    parameters: {
      query?: never;
      header: {
        /** @description Required quoted row version, for example "3" */
        "If-Match": string;
      };
      path: {
        draft_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  update_draft_api_v1_ticket_drafts__draft_id__patch: {
    parameters: {
      query?: never;
      header?: {
        /** @description Optional quoted row version, for example "3" */
        "If-Match"?: string | null;
      };
      path: {
        draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  submit_draft_api_v1_ticket_drafts__draft_id__submit_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "If-Match"?: string | null;
      };
      path: {
        draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftVersionRequest"];
      };
    };
    responses: {
      /** @description Identical idempotent replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  validate_draft_api_v1_ticket_drafts__draft_id__validate_post: {
    parameters: {
      query?: never;
      header?: {
        "If-Match"?: string | null;
      };
      path: {
        draft_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftVersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftValidationResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  get_ticket_api_v1_tickets__ticket_key__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  add_public_comment_api_v1_tickets__ticket_key__comments_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        ticket_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PublicCommentCreateRequest"];
      };
    };
    responses: {
      /** @description Identical idempotent replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketResponse"];
        };
      };
      /** @description Authentication required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Concurrency, configuration, or idempotency conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
      /** @description Structured validation failure */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemResponse"];
        };
      };
    };
  };
  liveness_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
